name: cmus # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '2.8.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: cmus — C* Music Player
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  cmus:
    command: usr/local/bin/cmus
    environment:
      PATH: $PATH:$SNAP/usr/local/
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      ALSA_CONFIG_PATH: /snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa/alsa.conf
      LANG: C.UTF-8
    plugs:
      - home
      - removable-media
      - pulseaudio
      - network
      - network-bind
      - audio-playback
      - alsa

parts:
  cmus:
    plugin: make
    source: https://github.com/cmus/cmus.git
    build-packages:
      - git
      - make
      - build-essential
      - libmad0-dev
      - libncursesw5-dev
      - libncurses5-dev
      - libpulse-dev
      - libasound2-dev
      - libroar-dev
      - libao-dev
      - libjack-dev
      - libsamplerate0-dev
      - libcdio-dev
      - libcdio-cdda-dev
      - libcddb2-dev
      - libcue-dev
      - libflac-dev
      - libvorbis-dev
      - libmpcdec-dev
      - libwavpack-dev
      - libavformat-dev 
      - libavcodec-dev
      - libfaad-dev
      - libmodplug-dev
      - libmikmod2-dev
      - libsndio-dev
      - libdiscid-dev
      - libopusfile-dev
      - libsystemd-dev
    override-build: |
      sudo apt instal libdiscid0
      ./configure
      make 
      make install DESTDIR=$SNAPCRAFT_PART_INSTALL
    stage-packages:
      - libaudio2
      - libao4
      - libaom0
      - libasound2
      - libasyncns0
      - libavcodec58
      - libavformat58
      - libavutil56
      - libbluray2
      - libcairo-gobject2
      - libcairo2
      - libcddb2
      - libcdio-cdda2
      - libcdio18
      - libchromaprint1
      - libcodec2-0.9
      - libdatrie1
      - libdiscid0
      - libdrm2
      - libfaad2
      - libflac8
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgdk-pixbuf2.0-0
      - libgme0
      - libgomp1
      - libgraphite2-3
      - libgsm1
      - libharfbuzz0b
      - libicu66
      - libjack0
      - libmad0
      - libmodplug1
      - libmp3lame0
      - libmpcdec6
      - libmpg123-0
      - libnuma1
      - libogg0
      - libopenjp2-7
      - libopenmpt0
      - libopus0
      - libopusfile0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libpulse0
      - libroar2
      - librsvg2-2
      - libsamplerate0
      - libshine3
      - libsnappy1v5
      - libsndfile1
      - libsndio7.0
      - libsoxr0
      - libspeex1
      - libssh-gcrypt-4
      - libswresample3
      - libthai0
      - libtheora0
      - libtwolame0
      - libva-drm2
      - libva-x11-2
      - libva2
      - libvdpau1
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libvpx6
      - libwavpack1
      - libwebp6
      - libwebpmux3
      - libx11-6
      - libx264-155
      - libx265-179
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxml2
      - libxrender1
      - libxvidcore4
      - libzvbi0
      - ocl-icd-libopencl1
    # prime:
    #   - usr/local/lib/cmus/ip
    #   - usr/local/lib/cmus/op
